#cloud-config
debug:
  verbose: true
bootcmd:
  - echo 'boot cmd execute' >> /etc/cmds
runcmd:
  - echo 'runcmd done' >> /etc/cmds
chpasswd: { expire: False }
{% if skyway_edge_vm_password is defined %}
chpasswd:
  list: |
    root:{{ skyway_edge_vm_password }}
    {{ skyway_edge_vm_user }}:{{ skyway_edge_vm_password }}
  expire: False
{% endif %}
ssh_pwauth: yes
users:
  - name: {{ skyway_edge_vm_user }}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,wheel
    lock_passwd: false
    ssh-authorized-keys:
      - {{ skyway_edge_vm_ssh_pub_key | trim() | regex_replace('\\n','') }}
    shell: /bin/bash
hostname: {{ vm_name }}
final_message: 'System is up after $UPTIME sec using $DATASOURCE and $VERSION'
ntp:
  enabled: true
packages:
  - curl
  - open-vm-tools
  - python-setuptools
  - python2.7
  - python2.7-dev
  - unzip
apt_update: true
apt_upgrade: true
apt_reboot_if_required: true
manage_resolv_conf: true
resolv_conf:
{% if dnsserver is defined and dnsserver is not none %}
    nameservers: ['{{ dnsserver }}']
{% else %}
    nameservers: ['8.8.4.4', '8.8.8.8']
{% endif %}
growpart:
  mode: auto
  devices: ['/']
